export const state = {
  currentScreen: 'home',
  capturedPhotos: [],
  reviewContext: null,
  captureDraft: {
    habitat: '',
    notes: '',
    uncertain: false,
    visibility: 'public',
  },
  batchCount: 0,
  sessionStart: null,
  gps: null,
  cameraStream: null,
  user: null,
  cloudPlan: null,
  searchQuery: '',
  findsView: 'cards',
  findsGroupBySpecies: false,
  findsUncertainOnly: false,
  findsSporesOnly: false,
  findsTargetUserId: null,
  findsTargetUsername: null,
  findsTargetAvatarUrl: null,
}
