export const state = {
  currentScreen: 'home',
  capturedPhotos: [],
  reviewContext: null,
  captureDraft: {
    habitat: '',
    notes: '',
    uncertain: false,
    is_draft: true,
    location_precision: 'exact',
    visibility: 'public',
  },
  batchCount: 0,
  sessionStart: null,
  gps: null,
  cameraStream: null,
  user: null,
  cloudPlan: null,
  searchQuery: '',
  observationScope: 'mine',
  findsView: 'cards',
  findsGroupBySpecies: false,
  findsSporesOnly: false,
  findsDraftOnly: false,
  findsTargetUserId: null,
  findsTargetUsername: null,
  findsTargetAvatarUrl: null,
  findsTargetDisplayName: null,
  findsTargetBio: null,
  findsTargetFinds: 0,
  findsTargetSpecies: 0,
  findsTargetSpores: 0,
}
