-- Public observation spore mosaic / atlas storage.
--
-- Replaces the per-spore `spore_measurements.thumb_key` fallback with a single
-- per-observation atlas image + a tile manifest. The public RPC keeps
-- `cropUrl` as a fallback so existing observations without a mosaic keep
-- working.
--
-- Two tables:
--   * spore_measurement_mosaics       — one row per (observation, version).
--   * spore_measurement_mosaic_tiles  — one row per measurement, pointing at
--                                       its tile rectangle inside the mosaic.
--
-- Writes are owner-scoped (sporely-py syncs as the owning user, same as
-- spore_measurements). Public reads only happen through the
-- get_public_observation RPC below, which re-gates on visibility.

CREATE TABLE IF NOT EXISTS public.spore_measurement_mosaics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id bigint NOT NULL REFERENCES public.observations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  storage_key text NOT NULL,
  width_px integer NOT NULL,
  height_px integer NOT NULL,
  tile_size_px integer NOT NULL,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (observation_id, version),
  CHECK (width_px > 0 AND height_px > 0 AND tile_size_px > 0)
);

CREATE INDEX IF NOT EXISTS spore_measurement_mosaics_observation_id_idx
  ON public.spore_measurement_mosaics (observation_id);

CREATE TABLE IF NOT EXISTS public.spore_measurement_mosaic_tiles (
  measurement_id bigint PRIMARY KEY REFERENCES public.spore_measurements(id) ON DELETE CASCADE,
  mosaic_id bigint NOT NULL REFERENCES public.spore_measurement_mosaics(id) ON DELETE CASCADE,
  x_px integer NOT NULL,
  y_px integer NOT NULL,
  w_px integer NOT NULL,
  h_px integer NOT NULL,
  overlay_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (x_px >= 0 AND y_px >= 0 AND w_px > 0 AND h_px > 0)
);

CREATE INDEX IF NOT EXISTS spore_measurement_mosaic_tiles_mosaic_id_idx
  ON public.spore_measurement_mosaic_tiles (mosaic_id);

ALTER TABLE public.spore_measurement_mosaics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spore_measurement_mosaic_tiles ENABLE ROW LEVEL SECURITY;

-- Owner-scoped writes on the mosaic table (parallels spore_measurements).
-- Every policy also verifies that observation_id belongs to auth.uid() so an
-- authenticated user cannot attach a mosaic (with their own user_id) to
-- someone else's public observation. Without that second check the public
-- RPC would happily serve the attacker's storage_key for a victim's
-- observation.
CREATE POLICY "Users can view their own spore mosaics"
  ON public.spore_measurement_mosaics FOR SELECT
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.observations o
      WHERE o.id = spore_measurement_mosaics.observation_id
        AND o.user_id = auth.uid()
    )
  );
CREATE POLICY "Users can insert their own spore mosaics"
  ON public.spore_measurement_mosaics FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.observations o
      WHERE o.id = spore_measurement_mosaics.observation_id
        AND o.user_id = auth.uid()
    )
  );
CREATE POLICY "Users can update their own spore mosaics"
  ON public.spore_measurement_mosaics FOR UPDATE
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.observations o
      WHERE o.id = spore_measurement_mosaics.observation_id
        AND o.user_id = auth.uid()
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.observations o
      WHERE o.id = spore_measurement_mosaics.observation_id
        AND o.user_id = auth.uid()
    )
  );
CREATE POLICY "Users can delete their own spore mosaics"
  ON public.spore_measurement_mosaics FOR DELETE
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.observations o
      WHERE o.id = spore_measurement_mosaics.observation_id
        AND o.user_id = auth.uid()
    )
  );

-- Tiles are gated through their parent mosaic AND require the measurement to
-- live on an image of the mosaic's observation. Without the observation-scope
-- check a caller could attach tile rows referencing measurements from an
-- unrelated observation (breaking the RPC's overlay semantics even if the
-- caller owns both sides).
CREATE POLICY "Users can view tiles for their own mosaics"
  ON public.spore_measurement_mosaic_tiles FOR SELECT
  USING (EXISTS (
    SELECT 1
    FROM public.spore_measurement_mosaics sm
    JOIN public.spore_measurements meas
      ON meas.id = spore_measurement_mosaic_tiles.measurement_id
    JOIN public.observation_images img
      ON img.id = meas.image_id
    WHERE sm.id = spore_measurement_mosaic_tiles.mosaic_id
      AND sm.user_id = auth.uid()
      AND img.observation_id = sm.observation_id
  ));
CREATE POLICY "Users can insert tiles for their own mosaics"
  ON public.spore_measurement_mosaic_tiles FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1
    FROM public.spore_measurement_mosaics sm
    JOIN public.spore_measurements meas
      ON meas.id = spore_measurement_mosaic_tiles.measurement_id
    JOIN public.observation_images img
      ON img.id = meas.image_id
    WHERE sm.id = spore_measurement_mosaic_tiles.mosaic_id
      AND sm.user_id = auth.uid()
      AND img.observation_id = sm.observation_id
  ));
CREATE POLICY "Users can update tiles for their own mosaics"
  ON public.spore_measurement_mosaic_tiles FOR UPDATE
  USING (EXISTS (
    SELECT 1
    FROM public.spore_measurement_mosaics sm
    JOIN public.spore_measurements meas
      ON meas.id = spore_measurement_mosaic_tiles.measurement_id
    JOIN public.observation_images img
      ON img.id = meas.image_id
    WHERE sm.id = spore_measurement_mosaic_tiles.mosaic_id
      AND sm.user_id = auth.uid()
      AND img.observation_id = sm.observation_id
  ))
  WITH CHECK (EXISTS (
    SELECT 1
    FROM public.spore_measurement_mosaics sm
    JOIN public.spore_measurements meas
      ON meas.id = spore_measurement_mosaic_tiles.measurement_id
    JOIN public.observation_images img
      ON img.id = meas.image_id
    WHERE sm.id = spore_measurement_mosaic_tiles.mosaic_id
      AND sm.user_id = auth.uid()
      AND img.observation_id = sm.observation_id
  ));
CREATE POLICY "Users can delete tiles for their own mosaics"
  ON public.spore_measurement_mosaic_tiles FOR DELETE
  USING (EXISTS (
    SELECT 1
    FROM public.spore_measurement_mosaics sm
    JOIN public.spore_measurements meas
      ON meas.id = spore_measurement_mosaic_tiles.measurement_id
    JOIN public.observation_images img
      ON img.id = meas.image_id
    WHERE sm.id = spore_measurement_mosaic_tiles.mosaic_id
      AND sm.user_id = auth.uid()
      AND img.observation_id = sm.observation_id
  ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.spore_measurement_mosaics TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.spore_measurement_mosaic_tiles TO authenticated;

-- ─── RPC extension ──────────────────────────────────────────────────────────
-- Add `sporeMosaic` at the top level and extend each `sporePoints` element
-- with mosaic tile coordinates + tile-local overlay geometry when available.
-- Both remain nullable — legacy observations without a mosaic still get
-- ordinary `sporePoints` with the `cropUrl` fallback.

DROP FUNCTION IF EXISTS public.get_public_observation(bigint);

CREATE FUNCTION public.get_public_observation(
  p_observation_id bigint
)
RETURNS TABLE(
  id bigint,
  "speciesSlug" text,
  "speciesName" text,
  "speciesCommonName" text,
  "observerDisplayName" text,
  "observedOn" date,
  country text,
  "regionId" text,
  "locationPrecision" text,
  "locationLabel" text,
  "hasMicroscopy" boolean,
  "sporeMeasurementCount" bigint,
  "sporeSummary" jsonb,
  "sporePoints" jsonb,
  "sporeMosaic" jsonb,
  "contrastMethod" text,
  "mountReagent" text,
  "sampleType" text,
  "mapLat" double precision,
  "mapLon" double precision
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  WITH candidate_base AS (
    SELECT
      o.id,
      nullif(btrim(coalesce(o.genus, '')), '') AS genus,
      nullif(btrim(coalesce(o.species, '')), '') AS species,
      nullif(btrim(coalesce(o.common_name, '')), '') AS common_name,
      o.user_id,
      o.author,
      o.date AS observed_on,
      nullif(btrim(coalesce(o.country_code, '')), '') AS country,
      nullif(btrim(coalesce(o.region_id, '')), '') AS region_id,
      coalesce(o.location_precision, 'hidden') AS location_precision,
      nullif(btrim(coalesce(o.location, '')), '') AS location,
      nullif(btrim(coalesce(r.label, '')), '') AS region_label,
      public.community_contributor_label(o.user_id, o.author) AS observer_display_name
    FROM public.observations o
    LEFT JOIN public.public_regions r
      ON r.id = o.region_id
    WHERE o.id = p_observation_id
      AND o.visibility = 'public'::text
      AND NOT coalesce(o.is_draft, false)
      AND NOT EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE p.id = o.user_id
          AND p.is_banned = true
      )
      AND (
        auth.uid() IS NULL
        OR public.is_blocked_between(auth.uid(), o.user_id) IS NOT TRUE
      )
  ),
  enriched AS (
    SELECT
      c.*,
      latest_image.contrast AS contrast_method,
      latest_image.mount_medium AS mount_reagent,
      latest_image.sample_type AS sample_type,
      (latest_image.id IS NOT NULL) AS has_microscopy,
      CASE
        WHEN o.spore_data_visibility = 'public'::text
          THEN coalesce(spore_stats.spore_measurement_count, 0::bigint)
        ELSE 0::bigint
      END AS spore_measurement_count,
      CASE
        WHEN o.spore_data_visibility = 'public'::text
          THEN o.spore_statistics
        ELSE NULL::jsonb
      END AS spore_summary,
      CASE
        WHEN o.spore_data_visibility = 'public'::text
          THEN point_agg.spore_points
        ELSE NULL::jsonb
      END AS spore_points,
      CASE
        WHEN o.spore_data_visibility = 'public'::text
             AND latest_mosaic.id IS NOT NULL
          THEN jsonb_build_object(
            'url',      concat('https://media.sporely.no/', latest_mosaic.storage_key),
            'width',    latest_mosaic.width_px,
            'height',   latest_mosaic.height_px,
            'tileSize', latest_mosaic.tile_size_px,
            'version',  latest_mosaic.version
          )
        ELSE NULL::jsonb
      END AS spore_mosaic,
      CASE
        WHEN c.location_precision = 'exact'::text
          THEN o.gps_latitude
        WHEN c.location_precision = 'fuzzed'::text
          THEN round(o.gps_latitude::numeric, 2)::double precision
        ELSE NULL::double precision
      END AS map_lat,
      CASE
        WHEN c.location_precision = 'exact'::text
          THEN o.gps_longitude
        WHEN c.location_precision = 'fuzzed'::text
          THEN round(o.gps_longitude::numeric, 2)::double precision
        ELSE NULL::double precision
      END AS map_lon
    FROM candidate_base c
    JOIN public.observations o
      ON o.id = c.id
    LEFT JOIN LATERAL (
      SELECT
        i.id,
        i.contrast,
        i.mount_medium,
        i.sample_type
      FROM public.observation_images i
      WHERE i.observation_id = c.id
        AND i.deleted_at IS NULL
        AND i.purged_at IS NULL
        AND (
          i.image_type = 'microscope'::text
          OR (
            i.image_type IS NULL
            AND EXISTS (
              SELECT 1
              FROM public.spore_measurements m2
              WHERE m2.image_id = i.id
                AND (
                  m2.measurement_type IS NULL
                  OR m2.measurement_type = ''
                  OR lower(m2.measurement_type) IN ('manual', 'spore', 'spores')
                )
            )
          )
        )
      ORDER BY i.created_at DESC NULLS LAST, i.id DESC
      LIMIT 1
    ) latest_image ON true
    LEFT JOIN LATERAL (
      SELECT count(*)::bigint AS spore_measurement_count
      FROM public.observation_images i
      JOIN public.spore_measurements m
        ON m.image_id = i.id
      WHERE i.observation_id = c.id
        AND i.deleted_at IS NULL
        AND i.purged_at IS NULL
        AND (i.image_type IS NULL OR i.image_type = 'microscope'::text)
        AND (
          m.measurement_type IS NULL
          OR m.measurement_type = ''
          OR lower(m.measurement_type) IN ('manual', 'spore', 'spores')
        )
    ) spore_stats ON true
    LEFT JOIN LATERAL (
      -- Latest mosaic for this observation. Multiple versions may coexist;
      -- the RPC always projects the highest version.
      --
      -- Pin sm.user_id = c.user_id so a mosaic row must be owned by the same
      -- account as the observation. Table RLS already enforces this on writes,
      -- but the RPC is SECURITY DEFINER and bypasses RLS on reads — so the
      -- constraint has to be re-asserted here to avoid serving a mosaic that
      -- somehow ended up attached to another user's observation.
      SELECT
        sm.id,
        sm.storage_key,
        sm.width_px,
        sm.height_px,
        sm.tile_size_px,
        sm.version
      FROM public.spore_measurement_mosaics sm
      WHERE sm.observation_id = c.id
        AND sm.user_id = c.user_id
      ORDER BY sm.version DESC, sm.id DESC
      LIMIT 1
    ) latest_mosaic ON true
    LEFT JOIN LATERAL (
      -- Individual spore points. Each point may carry mosaic tile
      -- coordinates + overlay geometry when a tile row exists in the
      -- latest mosaic; otherwise those fields are omitted.
      SELECT jsonb_agg(
        (
          jsonb_build_object(
            'id',            m.id::text,
            'observationId', c.id::text,
            'imageId',       i.id::text,
            'lengthUm',      m.length_um,
            'widthUm',       m.width_um,
            'q',             round((m.length_um / nullif(m.width_um, 0))::numeric, 4)::double precision,
            'cropUrl',       CASE
                               WHEN m.thumb_key IS NOT NULL
                                 THEN concat('https://media.sporely.no/', m.thumb_key)
                               ELSE NULL
                             END
          )
          || CASE
               WHEN t.measurement_id IS NOT NULL
                 THEN jsonb_build_object(
                   'mosaicX', t.x_px,
                   'mosaicY', t.y_px,
                   'mosaicW', t.w_px,
                   'mosaicH', t.h_px
                 )
                 || CASE
                      WHEN t.overlay_json IS NOT NULL
                        THEN jsonb_build_object('overlay', t.overlay_json)
                      ELSE '{}'::jsonb
                    END
               ELSE '{}'::jsonb
             END
        )
        ORDER BY m.id
      ) AS spore_points
      FROM public.observation_images i
      JOIN public.spore_measurements m
        ON m.image_id = i.id
      LEFT JOIN public.spore_measurement_mosaic_tiles t
        ON t.measurement_id = m.id
       AND t.mosaic_id = latest_mosaic.id
      WHERE i.observation_id = c.id
        AND i.deleted_at IS NULL
        AND i.purged_at IS NULL
        AND (i.image_type IS NULL OR i.image_type = 'microscope'::text)
        AND m.length_um IS NOT NULL
        AND m.width_um IS NOT NULL
        AND (
          m.measurement_type IS NULL
          OR m.measurement_type = ''
          OR lower(m.measurement_type) IN ('manual', 'spore', 'spores')
        )
    ) point_agg ON true
  )
  SELECT
    e.id AS id,
    nullif(
      regexp_replace(
        regexp_replace(lower(btrim(concat_ws(' ', e.genus, e.species))), '[^a-z0-9]+', '-', 'g'),
        '(^-|-$)',
        '',
        'g'
      ),
      ''
    ) AS "speciesSlug",
    nullif(btrim(concat_ws(' ', e.genus, e.species)), '') AS "speciesName",
    e.common_name AS "speciesCommonName",
    e.observer_display_name AS "observerDisplayName",
    e.observed_on AS "observedOn",
    e.country AS country,
    e.region_id AS "regionId",
    e.location_precision AS "locationPrecision",
    CASE
      WHEN e.location_precision = 'exact'::text THEN e.location
      WHEN e.location_precision = 'fuzzed'::text THEN coalesce(e.region_label, e.country)
      WHEN e.location_precision = 'region'::text THEN e.region_label
      ELSE NULL::text
    END AS "locationLabel",
    e.has_microscopy AS "hasMicroscopy",
    e.spore_measurement_count AS "sporeMeasurementCount",
    e.spore_summary AS "sporeSummary",
    e.spore_points AS "sporePoints",
    e.spore_mosaic AS "sporeMosaic",
    e.contrast_method AS "contrastMethod",
    e.mount_reagent AS "mountReagent",
    nullif(lower(btrim(coalesce(e.sample_type, ''))), '') AS "sampleType",
    e.map_lat AS "mapLat",
    e.map_lon AS "mapLon"
  FROM enriched e
  LIMIT 1
$$;

ALTER FUNCTION public.get_public_observation(bigint) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.get_public_observation(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_observation(bigint) TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_observation(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_observation(bigint) TO service_role;

NOTIFY pgrst, 'reload schema';
