create table if not exists public.observation_identifications (
  id bigint generated by default as identity primary key,

  observation_id bigint not null references public.observations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,

  service text not null,
  source text not null default 'ai',
  status text not null default 'success',

  image_fingerprint text not null default '',
  crop_fingerprint text,
  request_fingerprint text not null,

  language text,
  model_version text,

  results jsonb not null default '[]'::jsonb,

  top_scientific_name text,
  top_vernacular_name text,
  top_taxon_id text,
  top_probability numeric,

  error_message text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint observation_identifications_service_check
    check (service in ('artsorakel', 'inat', 'inaturalist')),

  constraint observation_identifications_status_check
    check (status in ('success', 'no_match', 'error', 'stale', 'unavailable')),

  constraint observation_identifications_probability_check
    check (top_probability is null or (top_probability >= 0 and top_probability <= 1)),

  constraint observation_identifications_unique_run
    unique (observation_id, service, request_fingerprint)
);

create index if not exists observation_identifications_observation_idx
  on public.observation_identifications (observation_id, created_at desc);

create index if not exists observation_identifications_user_idx
  on public.observation_identifications (user_id, created_at desc);

create index if not exists observation_identifications_service_idx
  on public.observation_identifications (observation_id, service, created_at desc);

alter table public.observation_identifications enable row level security;

drop policy if exists "Users can read own observation identifications"
  on public.observation_identifications;

create policy "Users can read own observation identifications"
  on public.observation_identifications
  for select
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.observations o
      where o.id = observation_identifications.observation_id
        and o.user_id = auth.uid()
    )
  );

drop policy if exists "Users can insert own observation identifications"
  on public.observation_identifications;

create policy "Users can insert own observation identifications"
  on public.observation_identifications
  for insert
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.observations o
      where o.id = observation_identifications.observation_id
        and o.user_id = auth.uid()
    )
  );

drop policy if exists "Users can update own observation identifications"
  on public.observation_identifications;

create policy "Users can update own observation identifications"
  on public.observation_identifications
  for update
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.observations o
      where o.id = observation_identifications.observation_id
        and o.user_id = auth.uid()
    )
  )
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.observations o
      where o.id = observation_identifications.observation_id
        and o.user_id = auth.uid()
    )
  );

drop policy if exists "Users can delete own observation identifications"
  on public.observation_identifications;

create policy "Users can delete own observation identifications"
  on public.observation_identifications
  for delete
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.observations o
      where o.id = observation_identifications.observation_id
        and o.user_id = auth.uid()
    )
  );

notify pgrst, 'reload schema';
